export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA'
export const UPDATE_STATE = 'UPDATE_STATE'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

