export const SET_USER = "SET_USER";
export const SET_USER_DATA = "SET_USER_DATA";
export const RESET_USER = "RESET_USER";
export const RESET_STATE = "RESET_STATE";
export const SET_STATE = "SET_STATE";
export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const SET_SIDEBAR_OPEN = "SET_SIDEBAR_OPEN";
export const SET_EXPIRY = "SET_EXPIRY";
export const SET_ADMIN = "SET_ADMIN ";
